services:
  - type: web
    name: xmr-backend
    runtime: python3
    preBuildCommand: apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 2 --worker-class sync --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
